 name: Update Monkeytype Stats
    on:
      schedule:
        # Runs every day at 00:00 UTC
        - cron: '0 0 * * *'
      workflow_dispatch:

    jobs:
      update-readme:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: monkeytypegame/monkeytype-readme@v1.0.0 # Or the latest version
            with:
              MONKEYTYPE_USERNAME: indrajeetbohra # Replace with your Monkeytype username
              MONKEYTYPE_THEME_NAME: discord # Optional: Replace with your preferred theme (e.g., nord_light)
              BRANCH_NAME: main # Or the branch where your README is located
